#To enable an arrow type, uncomment the line by removing
# the #. 
#
#Costs are given in the format ITEM_NAME:AMOUNT
#For arrows that have multiple requirements, separate them
#with a comma. 
#
#EX: Frag: TNT:1,Dirt:1,Water Bucket:64

#GlassHead: Glass:1
#APmax: Iron Ingot:3,Obsidian:1
#Torch: Torch:1
#Net: String:9
#Water: Water Bucket:1
#Fire: Torch:1,Coal:1
#Lightning: Emerald:1,Iron Ingot:1,Magma Cream:1
#Mudslinger: Dirt:1
#Warp: Ender Pearl:1
#Poison: Spider Eye:3,Red Mushroom:3,Brown Mushroom:3
#Frag: TNT:1
#Impact: TNT:1
#Bugbomb: Spider Eye:1,Sugar:10
#PlanetCracker: Ghast Tear:1,Eye_Of_Ender:1,TNT:5,Redstone:5