name: Barrage
author: MooseOnTehLoose
main: net.moosecraft.Barrage.Barrage
version: 2.1-1.20.2
api-version: 1.20.2
commands:
   barrage:
      description: Upgrade your arsenal with a variety of specialty arrows
      usage: "instructions: https://github.com/MooseOnTehLoose/Barrage"
