name: Barrage
author: MooseOnTehLoose
main: net.moosecraft.Barrage.Barrage
version: 2.2-1.20.4
api-version: 1.20
commands:
   barrage:
      description: Upgrade your arsenal with a variety of specialty arrows
      usage: "instructions: https://github.com/MooseOnTehLoose/Barrage"